In [4]:
import numpy as np
a = np.array([3,1])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(2,)
2
int32


In [5]:
b = np.array([[3,1]])
print(b.shape)

(1, 2)


In [24]:
arr = np.array([[2,3,1], [5,3,4]])
print(arr.shape)

(2, 3)


In [8]:
arr = arr.reshape(3,2)
print(arr)
print(arr.shape)

[[2 3]
 [1 5]
 [6 4]]
(3, 2)


In [26]:
arr = arr.reshape(2,3)
print(arr)
print(arr[1][1])

[[2 3 1]
 [5 3 4]]
3


In [17]:
print(arr[1, 1:])

[6 4]


In [18]:
print(arr[arr < 3])

[2 1]


In [19]:
print(arr[arr>2])

[3 5 6 4]


In [31]:
l4 = np.nonzero(arr < 4)
print(l4)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 1], dtype=int64))


In [28]:
print(np.nonzero(arr > 10))

(array([], dtype=int64), array([], dtype=int64))


In [32]:
list_of_coordinates = list(zip(l4[0], l4[1])) 
print(list_of_coordinates)

[(0, 0), (0, 1), (0, 2), (1, 1)]


In [39]:
print(list(zip(l4[0], l4[1])))

[(0, 0), (0, 1), (0, 2), (1, 1)]


In [ ]:
x = np.array([1,2])
x

In [4]:
import numpy as np
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
print(a[-1:])

[[20 21 22 23 24]]


In [23]:
a[:,-2::-2]

array([[ 3,  1],
       [ 8,  6],
       [13, 11],
       [18, 16],
       [23, 21]])

In [30]:
a[1::2,::-2]

array([[ 9,  7,  5],
       [19, 17, 15]])

In [31]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [36]:
a[1::2,:3:2]

array([[ 5,  7],
       [15, 17]])

In [37]:
org = np.array([1,2,3,4,5])
org

array([1, 2, 3, 4, 5])

In [42]:
copy = org[:3]
copy

array([1, 2, 3])

In [43]:
copy[0] = 0
copy

array([0, 2, 3])

In [44]:
org

array([0, 2, 3, 0, 5])

In [45]:
org[-2] = 4
org

array([0, 2, 3, 4, 5])

In [47]:
copy = org.copy()

In [49]:
print(org)
print(copy)

[0 2 3 4 5]
[0 2 3 4 5]


In [50]:
copy[0] = 1

In [51]:
print(org)
print(copy)

[0 2 3 4 5]
[1 2 3 4 5]
