In [4]:
import numpy as np
a = np.array([3,1])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(2,)
2
int32


In [5]:
b = np.array([[3,1]])
print(b.shape)

(1, 2)


In [24]:
arr = np.array([[2,3,1], [5,3,4]])
print(arr.shape)

(2, 3)


In [8]:
arr = arr.reshape(3,2)
print(arr)
print(arr.shape)

[[2 3]
 [1 5]
 [6 4]]
(3, 2)


In [26]:
arr = arr.reshape(2,3)
print(arr)
print(arr[1][1])

[[2 3 1]
 [5 3 4]]
3


In [17]:
print(arr[1, 1:])

[6 4]


In [18]:
print(arr[arr < 3])

[2 1]


In [19]:
print(arr[arr>2])

[3 5 6 4]


In [31]:
l4 = np.nonzero(arr < 4)
print(l4)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 1], dtype=int64))


In [28]:
print(np.nonzero(arr > 10))

(array([], dtype=int64), array([], dtype=int64))


In [32]:
list_of_coordinates = list(zip(l4[0], l4[1])) 
print(list_of_coordinates)

[(0, 0), (0, 1), (0, 2), (1, 1)]


In [39]:
print(list(zip(l4[0], l4[1])))

[(0, 0), (0, 1), (0, 2), (1, 1)]


In [ ]:
x = np.array([1,2])
x