In [2]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
a2 = np.array([2,4,1,6,8,5])
print(a2)

[2 4 1 6 8 5]


In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
print(a[0])

1


In [9]:
print(a)

[1 2 3]


In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(a[0])

[1 2 3]


In [12]:
print(a[0][1])

2


In [ ]:
print(a[1])