In [1]:
import numpy as np
x = np.array([1,2])
y = np.array([3,4])
print(x+y)

[4 6]


In [3]:
print(x.shape)

(2,)


In [4]:
x = x.reshape(1,2)
y = y.reshape(1,2)
print(x+y)

[[4 6]]


In [5]:
print(x * y)

[[3 8]]


In [8]:
x = x.reshape(2,)
print(x)
print(y)
print(x * y)
print(y * x)

[1 2]
[[3 4]]
[[3 8]]
[[3 8]]


In [14]:
a  = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [15]:
print(a[1,0])

3


In [31]:
b = np.array([[4,5], [6,7]])

In [17]:
print(a+b)

[[ 5  7]
 [ 9 11]]


In [18]:
print(a * b)

[[ 4 10]
 [18 28]]


In [19]:
# scalar multiplication AKA broadcasting
c = a * b
print(0.5 * c)

[[ 2.  5.]
 [ 9. 14.]]


In [20]:
print(3 * a)

[[ 3  6]
 [ 9 12]]


In [36]:
# max,min, sum
print(a.sum())
print("The sum of elements in B is: ", b.sum())
print("the smallest element in B is: ", b.min())
print("the largest element in B is: ", b.max())

10
The sum of elements in B is:  22
the smallest element in B is:  4
the largest element in B is:  7


In [37]:
print(c.max(axis=0))

[18 28]


In [39]:
print(c.max(axis=1))

[10 28]


In [40]:
print(c.sum(axis=0))

[22 38]
